### ISSUE TITLE
Upload task v1 is not able to run on Linux agent

### ISSUE THREAD

**Issue by trinhpham** [marceloavf/digitalocean-tools-vsts#18]
## Bug Report

**Upload task v1 is not able to run on Linux agent**
<details><summary>The build output</summary>
<p> 

![image](https://user-images.githubusercontent.com/9128061/101749132-f4056d80-3aff-11eb-9d56-521af5c4d512.png)
```
2020-12-09T09:03:27.1895444Z ##[debug]Evaluating condition for step: 'Upload ***'
2020-12-09T09:03:27.1895843Z ##[debug]Evaluating: succeeded()
2020-12-09T09:03:27.1895944Z ##[debug]Evaluating succeeded:
2020-12-09T09:03:27.1896191Z ##[debug]=> True
2020-12-09T09:03:27.1896368Z ##[debug]Result: True
2020-12-09T09:03:27.1896518Z ##[section]Starting: Upload ***
2020-12-09T09:03:27.1898981Z ==============================================================================
2020-12-09T09:03:27.1899057Z Task         : DigitalOcean Spaces Upload
2020-12-09T09:03:27.1899116Z Description  : Upload file and folder content to DigitalOcean Spaces Bucket
2020-12-09T09:03:27.1899176Z Version      : 1.0.0
2020-12-09T09:03:27.1899225Z Author       : Marcelo Formentão
2020-12-09T09:03:27.1899293Z Help         : [More Information](https://github.com/marceloavf/digitalocean-tools-vsts) (Version 1.0.0).
2020-12-09T09:03:27.1899358Z ==============================================================================
2020-12-09T09:03:27.2028917Z ##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
2020-12-09T09:03:27.2040593Z ##[debug]System.Exception: The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
2020-12-09T09:03:27.2041920Z ##[section]Finishing: Upload ***
```

</p>
</details>
<details><summary>Agent info</summary>
<p>

![image](https://user-images.githubusercontent.com/9128061/101749889-d84e9700-3b00-11eb-9c35-ce1e15684a37.png)

</p>
</details>
- TFS 2018 (previous version of Azure DevOps Server) Version: 16.131.28507.4

## Expected behavior
The task runs ok on all agent OSes

## Additional contexts
The v0 version is still working

**Comment by marceloavf** [comment]
Hi, thanks for the feedback.

I'm using this task with multiple OS here, but I'm not using TFS.

Maybe it's something related to node execution since it was one of the main thing changed into task execution, I'll need to investigate.

https://github.com/marceloavf/digitalocean-tools-vsts/blob/3f875530c680fd2f2133de5582c75076e97f8111/Tasks/DigitalOceanSpacesDelete/task.json#L95-L97

**Comment by marceloavf** [comment]
All new agents will deprecate node 6 soon and Microsoft is requiring migrating to node 10, so it's not a bug anymore.

```
##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.
```
